package by.prokhorenko.controller.command;

public enum CommandName {
    REGISTRATION,
    SIGN_IN,
    ADD_TRANSACTION,
    GET_ALL_TRANSACTIONS,
    GET_ALL_TRANSACTIONS_IN_A_PERIOD,
    GET_ALL_INCOMES,
    GET_ALL_EXPENSES,
    GET_SUM_OF_ALL_EXPENSES,
    GET_SUM_OF_ALL_INCOMES,
    GET_SUM_OF_ALL_EXPENSES_IN_A_PERIOD,
    GET_SUM_OF_ALL_INCOMES_IN_A_PERIOD
}
